# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /afs/andrew.cmu.edu/usr17/tonyy/private/15418/15418-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /afs/andrew.cmu.edu/usr17/tonyy/private/15418/15418-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/andrew.cmu.edu/usr17/tonyy/private/15418/15418-project/CMakeFiles /afs/andrew.cmu.edu/usr17/tonyy/private/15418/15418-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /afs/andrew.cmu.edu/usr17/tonyy/private/15418/15418-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named branch

# Build rule for target.
branch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 branch
.PHONY : branch

# fast build rule for target.
branch/fast:
	$(MAKE) $(MAKESILENT) -f branch/CMakeFiles/branch.dir/build.make branch/CMakeFiles/branch.dir/build
.PHONY : branch/fast

#=============================================================================
# Target rules for targets named branch_impl

# Build rule for target.
branch_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 branch_impl
.PHONY : branch_impl

# fast build rule for target.
branch_impl/fast:
	$(MAKE) $(MAKESILENT) -f branch_impl/CMakeFiles/branch_impl.dir/build.make branch_impl/CMakeFiles/branch_impl.dir/build
.PHONY : branch_impl/fast

#=============================================================================
# Target rules for targets named cache_impl

# Build rule for target.
cache_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cache_impl
.PHONY : cache_impl

# fast build rule for target.
cache_impl/fast:
	$(MAKE) $(MAKESILENT) -f cache_impl/CMakeFiles/cache_impl.dir/build.make cache_impl/CMakeFiles/cache_impl.dir/build
.PHONY : cache_impl/fast

#=============================================================================
# Target rules for targets named cadss-engine

# Build rule for target.
cadss-engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cadss-engine
.PHONY : cadss-engine

# fast build rule for target.
cadss-engine/fast:
	$(MAKE) $(MAKESILENT) -f engine/CMakeFiles/cadss-engine.dir/build.make engine/CMakeFiles/cadss-engine.dir/build
.PHONY : cadss-engine/fast

#=============================================================================
# Target rules for targets named trace

# Build rule for target.
trace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trace
.PHONY : trace

# fast build rule for target.
trace/fast:
	$(MAKE) $(MAKESILENT) -f trace/CMakeFiles/trace.dir/build.make trace/CMakeFiles/trace.dir/build
.PHONY : trace/fast

#=============================================================================
# Target rules for targets named taskLib

# Build rule for target.
taskLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taskLib
.PHONY : taskLib

# fast build rule for target.
taskLib/fast:
	$(MAKE) $(MAKESILENT) -f trace/taskLib/CMakeFiles/taskLib.dir/build.make trace/taskLib/CMakeFiles/taskLib.dir/build
.PHONY : taskLib/fast

#=============================================================================
# Target rules for targets named processor

# Build rule for target.
processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 processor
.PHONY : processor

# fast build rule for target.
processor/fast:
	$(MAKE) $(MAKESILENT) -f processor/CMakeFiles/processor.dir/build.make processor/CMakeFiles/processor.dir/build
.PHONY : processor/fast

#=============================================================================
# Target rules for targets named processor_impl

# Build rule for target.
processor_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 processor_impl
.PHONY : processor_impl

# fast build rule for target.
processor_impl/fast:
	$(MAKE) $(MAKESILENT) -f processor_impl/CMakeFiles/processor_impl.dir/build.make processor_impl/CMakeFiles/processor_impl.dir/build
.PHONY : processor_impl/fast

#=============================================================================
# Target rules for targets named coherence

# Build rule for target.
coherence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coherence
.PHONY : coherence

# fast build rule for target.
coherence/fast:
	$(MAKE) $(MAKESILENT) -f coherence/CMakeFiles/coherence.dir/build.make coherence/CMakeFiles/coherence.dir/build
.PHONY : coherence/fast

#=============================================================================
# Target rules for targets named interconnect

# Build rule for target.
interconnect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interconnect
.PHONY : interconnect

# fast build rule for target.
interconnect/fast:
	$(MAKE) $(MAKESILENT) -f interconnect/CMakeFiles/interconnect.dir/build.make interconnect/CMakeFiles/interconnect.dir/build
.PHONY : interconnect/fast

#=============================================================================
# Target rules for targets named simpleCache

# Build rule for target.
simpleCache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simpleCache
.PHONY : simpleCache

# fast build rule for target.
simpleCache/fast:
	$(MAKE) $(MAKESILENT) -f simpleCache/CMakeFiles/simpleCache.dir/build.make simpleCache/CMakeFiles/simpleCache.dir/build
.PHONY : simpleCache/fast

#=============================================================================
# Target rules for targets named directory

# Build rule for target.
directory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 directory
.PHONY : directory

# fast build rule for target.
directory/fast:
	$(MAKE) $(MAKESILENT) -f directory/CMakeFiles/directory.dir/build.make directory/CMakeFiles/directory.dir/build
.PHONY : directory/fast

#=============================================================================
# Target rules for targets named d_coherence

# Build rule for target.
d_coherence: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 d_coherence
.PHONY : d_coherence

# fast build rule for target.
d_coherence/fast:
	$(MAKE) $(MAKESILENT) -f d_coherence/CMakeFiles/d_coherence.dir/build.make d_coherence/CMakeFiles/d_coherence.dir/build
.PHONY : d_coherence/fast

#=============================================================================
# Target rules for targets named cache_impl_final

# Build rule for target.
cache_impl_final: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cache_impl_final
.PHONY : cache_impl_final

# fast build rule for target.
cache_impl_final/fast:
	$(MAKE) $(MAKESILENT) -f cache_impl_final/CMakeFiles/cache_impl_final.dir/build.make cache_impl_final/CMakeFiles/cache_impl_final.dir/build
.PHONY : cache_impl_final/fast

#=============================================================================
# Target rules for targets named interconnect_impl

# Build rule for target.
interconnect_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interconnect_impl
.PHONY : interconnect_impl

# fast build rule for target.
interconnect_impl/fast:
	$(MAKE) $(MAKESILENT) -f interconnect_impl/CMakeFiles/interconnect_impl.dir/build.make interconnect_impl/CMakeFiles/interconnect_impl.dir/build
.PHONY : interconnect_impl/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... branch"
	@echo "... branch_impl"
	@echo "... cache_impl"
	@echo "... cache_impl_final"
	@echo "... cadss-engine"
	@echo "... coherence"
	@echo "... d_coherence"
	@echo "... directory"
	@echo "... interconnect"
	@echo "... interconnect_impl"
	@echo "... processor"
	@echo "... processor_impl"
	@echo "... simpleCache"
	@echo "... taskLib"
	@echo "... trace"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

